2025-01-01 is closed and is colored in OrangeRed /'Neujahrstag'/
2025-01-06 is closed and is colored in OrangeRed /'Heilige Drei Könige'/
2025-04-18 is closed and is colored in OrangeRed /'Karfreitag'/
2025-04-21 is closed and is colored in OrangeRed /'Ostermontag'/
2025-05-01 is closed and is colored in OrangeRed /'Tag der Arbeit'/
2025-05-29 is closed and is colored in OrangeRed /'Christi Himmelfahrt'/
2025-06-09 is closed and is colored in OrangeRed /'Pfingstmontag'/
2025-06-19 is closed and is colored in OrangeRed /'Fronleichnam'/
2025-08-08 is closed and is colored in OrangeRed /'Augsburger Friedensfest'/
2025-08-15 is closed and is colored in OrangeRed /'Mariä Himmelfahrt'/
2025-10-03 is closed and is colored in OrangeRed /'Tag der Deutschen Einheit'/
2025-11-01 is closed and is colored in OrangeRed /'Allerheiligen'/
2025-11-19 is closed and is colored in OrangeRed /'Buß- und Bettag'/
2025-12-25 is closed and is colored in OrangeRed /'1. Weihnachtstag'/
2025-12-26 is closed and is colored in OrangeRed /'2. Weihnachtstag'/